### PR TITLE
Use Godep to manage dependencies

### PR DESCRIPTION
**Pull request by JayH5**
- Clean up Travis file

This might seem crazy to check in all the deps... but it's seemingly the recommended way for now. Consul does it :p

### CODE REVIEW

**Comment by smn** [comment]
:+1: except the last commit seems to have a path issue?

**Comment by smn** [comment]
Nope not a path issue
not sure what's going on there?

**Comment by JayH5** [comment]
It's a flaky test (concurrency issue). It's been happening since #8 when the test was introduced. See [build  80](https://travis-ci.org/universalcore/logdriver/builds/82941817).

I think the problem is relying on the line number from tail which is [not guaranteed to be accurate](https://godoc.org/github.com/hpcloud/tail#Tail.Tell). :/

**Comment by smn** [comment]
:+1:

**Pull request merged**
